### ISSUE TITLE
Provide pure floss build flavor

### ISSUE THREAD

**Issue by krt16s** [jruesga/PhotoPhase#30]
Since 2.2.1 PhotoPhase requires non-free dependencies (Google's play-services) to build. Most likely this comes from supporting chromecasting, so I wont argue if this is necessary. Anyway: Is there a possibility to add a free-only build flavor that doesnt require play-services (by not supporting casting)?

**Comment by jruesga** [comment]
Yes, the app needs Google Play Service to have access to GCM to be able to awake the device when is casting to CC and device enters in doze mode. Anyway, I can try to create a build flavor without GCM. I will update this issue when is done.

**Comment by jruesga** [comment]
Master branch (16637572d9ea91821738593e3b697a1afae57657) has now 2 product flavors: floss and gms

FLOSS product flavor doesn't depends on Google play services, while GMS does. Let me know if it is enough for build the F-Droid version or if there are other requirements.

**Comment by TheLastProject** [comment]
@krt16s: Any update on this? I see F-Droid still has nev builds disabled with this message:

We can't build this version: The build for this version was manually disabled. Reason: Uses proprietary gcm dependency

**Comment by krt16s** [comment]
Whoops, slipped my mind. Sorry.


Ref: https://gitlab.com/fdroid/fdroiddata/commit/a1c7bf44ced90883a2c9ac6605512b3061046937
