### ISSUE TITLE
Android unsets app as wallpaper

### ISSUE THREAD

**Issue by TheLastProject** [jruesga/PhotoPhase#31]
No clue why, but on my Android 7 device, sometimes PhotoPhase randomly disappears as wallpaper and I suddenly have the default factory wallpaper again. This happens once or twice a day so is rather annoying. Any way I could help debug this? 

I'm running the F-Droid build.

**Comment by TheLastProject** [comment]
I just noticed F-Droid's version is still very outdated. May be related. I'll reopen this issue if F-Droid gets a newer build so I can check if it's still relevant 4 years later.

**Comment by jruesga** [comment]
In the meantime, if you need a recent version, all the published versions of the play store are in the release section of the repo https://github.com/jruesga/PhotoPhase/releases. All the contains the gms services and are signed with the release keys.
