### ISSUE TITLE
Preserve filename when resizing

### ISSUE THREAD

**Issue by OhSoGood** [jruesga/PhotoPhase#33]
Hi,

I've been using your app for years, and I've only one word: thank you!

I've a very simple suggestion: when creating a resized image, could the app name it using the original image (plus a suffix, if you need uniqueness)? 

Currently, when an image is resized, the resized image displayed is always named "VT-Compress (tm) Xing Technology [...]", which is quite a pitty. I so loose the possibility to double-tap and open the image in order to get its name (name of the painting, date of the photo, etc.).

Would it be possible?

**Comment by jruesga** [comment]
@OhSoGood the fact is that metadata exists for one reason. Resizer apps shouldn't touch the name metadata (they have other attributes like description or even custom ones iirc).
