### ISSUE TITLE
Bug found while trying to move photos from photophase into Vault in PhotoPhase Application:

### ISSUE THREAD

**Issue by huwaid** [jruesga/PhotoPhase#35]
#### Expected behavior

The app should be able to move photos from photophase into Vault just like we move photos from gallery into Vault.

#### Actual behavior

Whenever we try to move photos from photophase into Vault. It just lights up and goes back to the place where we started and is unable to move photos from photophase into Vault. 

#### How to reproduce

Launch the app. 

Press on Media option. 

Select Albums from the Pictures. 

Select any image from the pictures. 

Now click on the Share icon. 

Select "Move into Vault" option. 

It just lights up and stops working. 

* Application: PhotoPhase 2.7.0(Apache-2.0)
Version: 2.7.0
* Operating system: Android Naugat. 
Redmi 5a

#### Recording Of The Bug

https://youtu.be/dvxnaL3jn58
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@huwaid/bug-found-while-trying-to-move-photos-from-photophase-into-vault-in-photophase-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jruesga** [comment]
@huwaid I did't find the Vault app you refer in your issue in the Play Store. Do you have a link to the app or the full qualified name of the app, or a logcat of the photophase when you share the picture through Vault? Thx

**Comment by jruesga** [comment]
Ok. I found it: AppLock (https://play.google.com/store/apps/details?id=com.domobile.applock). This apps tries to move a photo to hide from the system. PhotoPhase only provides a temporary read-only provider, so other apps can read the photo, but doesn't allow other apps to perform write operations on the underlying image. This is not a bug. It's the desired behaviour.

**Comment by huwaid** [comment]
Whatever it is..... Its not working properly!
So in that case it is a bug
